# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  - "3.7"
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt

addons:
  sonarcloud:
    organization: "excited-ccccly-github" # the key of the org you chose at step #3
# Command to run tests, e.g. python setup.py test
script:
  - make coverage
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'


