# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.7"
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - make coverage


